/*
 * This source file was generated by the Gradle 'init' task
 */
package org.errorsolver.topik8;

import org.errorsolver.topik8.components.CustomFrame;
import org.errorsolver.topik8.components.CustomPanel;
import org.errorsolver.topik8.components.LoadCSV;
import org.errorsolver.topik8.components.TableMhs;

public class App {

    public static void main(String[] args) {
        String fileName = "data-mahasiswa.csv";
        LoadCSV csv = new LoadCSV(fileName);
        String[] header = csv.getHeader();
        String[][] data = csv.getDatas();

        TableMhs tableMhs = new TableMhs(header, data);
        CustomFrame customFrame = new CustomFrame("Data Mahasiswa", 800, 600);
        customFrame.createFrame();

        CustomPanel cPanel = new CustomPanel(tableMhs, header);

        customFrame.add(cPanel.getComboBox(), "North");
        customFrame.add(tableMhs.getScrollPane(), "Center");
        customFrame.setVisible(true);
    }
}
