/*
 * This source file was generated by the Gradle 'init' task
 */
package org.errorsolver.topik8;

import javax.swing.BoxLayout;

import org.errorsolver.topik8.components.CustomFrame;
import org.errorsolver.topik8.components.CustomPanel;
import org.errorsolver.topik8.components.LoadCSV;
import org.errorsolver.topik8.components.TableMhs;

public class App {

    private final static String APP_TITLE = "Data Mahasiswa";
    private final static int APP_WIDTH = 800;
    private final static int APP_HEIGHT = 600;
    private final static int APP_LAYOUT = BoxLayout.Y_AXIS;
    private final static String FILE_NAME = "data-mahasiswa.csv";

    public static void main(String[] args) {
        LoadCSV csv = new LoadCSV(FILE_NAME);
        String[] header = csv.getHeader();
        String[][] data = csv.getDatas();

        TableMhs tableMhs = new TableMhs(header, data);

        CustomPanel sortingPanel = new CustomPanel(tableMhs, header);
        CustomFrame mainFrame = new CustomFrame(APP_TITLE, APP_WIDTH, APP_HEIGHT, APP_LAYOUT, sortingPanel, tableMhs.getScrollPane());
    }
}
